name: Python Application CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:     # to allow manual run

jobs:
  build:
    runs-on: self-hosted # changed from ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Debug PATH
      run: |
        echo $PATH
        which -a pip

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Dependencies
      # This is the requirement: trigger pip install -r requirements.txt
      # --require-hashes enforces the Chain of Trust
      run: |
        # python -m pip install --upgrade pip
        pip install --upgrade pip
        pip install --require-hashes -r requirements.txt

    # - name: 2. Gitleaks (Secret Scan)
    #  uses: gitleaks/gitleaks-action@v2
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: 3. Trivy (Config Scan)
    #  uses: aquasecurity/trivy-action@master
    #  with:
    #    scan-type: 'fs'
    #    exit-code: '1' # Fails PR if critical issues are found   

    - name: Safety Audit (Native Python)
      run: |
        pip install safety
        safety check --key ${{ secrets.SAFETY_API_KEY }}

      # Code below is ok but not for Azure so comment it out  
      # uses: pyupio/safety-action@v1        
      # with:
        # api-key: ${{ secrets.SAFETY_API_KEY }}

    - name: Run Application
      run: python app.py        